app = 'wv-gov-flights'
primary_region = 'iad'

[build]

[processes]
  app = 'node server.js'

[[services]]
  processes = ['app']
  internal_port = 3000
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1
  force_https = true
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    grace_period = "30s"
    tls_skip_verify = false

[[vm]]
  size = 'shared-cpu-1x'
